Repository masai-oss/Masai_Refresh, pull requests merged in 2021-04, with the labels that each got.

#178 next button color changed
  client/web/src/Structure/Common/DialogBoxes/ReportDialog.jsx
  client/web/src/Structure/Questions/Styles/QuestionStyles.jsx
Labels: frontend

#189 added dots and some UI
  client/web/src/Structure/Common/AlertPopUps/CustomizedSnackbars.jsx
  client/web/src/Structure/Common/Dots.jsx
  client/web/src/Structure/Common/Styles/ReportDialogBoxStyles.js
  client/web/src/Structure/Questions/Components/MCQ.jsx
  client/web/src/Structure/Questions/Styles/OptionStyles.jsx
  client/web/src/Structure/Questions/Styles/QuestionStyles.jsx
  client/web/src/Structure/Results Display/Components/Results_display.jsx
  client/web/src/Structure/Results Display/Styles/ResultsPageStyle.js
  client/web/src/Structure/Topics/Components/TopicCard.jsx
  client/web/src/Structure/Topics/Components/TopicWrapper.jsx
  client/web/src/Structure/Topics/Styles/TopicStyles.jsx
Labels: enhancement, frontend

#193 added required changes
  client/web/src/Structure/Topics/Components/TopicCard.jsx
  client/web/src/Structure/Topics/Components/TopicWrapper.jsx
  client/web/src/Structure/Topics/Styles/TopicStyles.jsx
Labels: enhancement, frontend

#201 source link updated
  client/web/src/Structure/Results Display/Components/DetailedReport.jsx
  client/web/src/Structure/Results Display/Styles/ModalStyles.jsx
Labels: enhancement

#206 optimised result api
  client/web/src/Structure/Common/Dots.jsx
  server/resources/controller/resultController.js
Labels: api, backend

#208 updated imports
  client/web/src/Structure/Admin/Components/CrudTopics.jsx
  client/web/src/Structure/Admin/Components/QuestionForm.jsx
  client/web/src/Structure/Admin/Components/Questions.jsx
  client/web/src/Structure/Admin/Components/QuestionsByTopic.jsx
  client/web/src/Structure/Admin/Components/Row.jsx
  client/web/src/Structure/Admin/Components/SearchByTopic.jsx
  client/web/src/Structure/Authentication/Login.jsx
  client/web/src/Structure/Common/AlertPopUps/CustomizedSnackbars.jsx
  client/web/src/Structure/Common/DialogBoxes/ReportDialog.jsx
  client/web/src/Structure/Common/IsLoading.jsx
  client/web/src/Structure/Common/LoadingButton.jsx
  client/web/src/Structure/Common/Navbar2.jsx
  client/web/src/Structure/Common/PageNotFound.jsx
  client/web/src/Structure/Common/index.js
  client/web/src/Structure/Navbar/Navbar.jsx
  client/web/src/Structure/Questions/Components/MCQ.jsx
  client/web/src/Structure/Questions/Questions.jsx
  client/web/src/Structure/Results Display/Components/DetailedReport.jsx
  client/web/src/Structure/Results Display/Components/ModalReport.jsx
  client/web/src/Structure/Results Display/Components/Results_display.jsx
  client/web/src/Structure/Results Display/index.js
  client/web/src/Structure/Topics/Components/TopicWrapper.jsx
  client/web/src/Structure/Topics/Components/startQuizModal.jsx
  client/web/src/Structure/Topics/Topics.jsx
Labels: enhancement, frontend

#211 removed problem in dots
  client/web/src/App.Styles.js
  client/web/src/App.js
  client/web/src/App.module.css
  client/web/src/Structure/Authentication/Login.jsx
  client/web/src/Structure/Common/DotsLogo.jsx
  client/web/src/Structure/Common/Loader.jsx
  client/web/src/Structure/Common/Styles/DotsStyles.js
  client/web/src/Structure/Common/index.js
  client/web/src/Structure/Results Display/Components/Results_display.jsx
  client/web/src/index.js
Labels: enhancement, frontend

#216 optimised proficiency
  server/resources/controller/proficiencyController.js
  server/resources/routes/topicRoute.js
Labels: api, backend

#221 create quiz optimised
  server/resources/controller/attemptController.js
  server/resources/controller/topicController.js
  server/resources/routes/attemptRoute.js
Labels: api, backend

#225 cleared
  server/resources/controller/attemptController.js
  server/resources/controller/proficiencyController.js
  server/resources/controller/questionController.js
  server/resources/controller/reportController.js
  server/resources/controller/resultController.js
  server/resources/controller/topicController.js
  server/resources/models/Submission.js
  server/resources/models/User.js
  server/resources/routes/attemptRoute.js
  server/resources/routes/questionRoute.js
  server/resources/routes/topicRoute.js
Labels: api, backend, basic-working

#226 Rebuild Question CRUD, Result API, Report API
  client/web/package-lock.json
  server/resources/controller/questionController.js
  server/resources/controller/reportController.js
  server/resources/controller/resultController.js
  server/resources/models/Question.js
  server/resources/models/User.js
  server/resources/routes/attemptRoute.js
  server/resources/routes/questionRoute.js
  server/resources/routes/topicRoute.js
  server/resources/routes/userAuthRoute.js
  server/resources/services/googleStrategy.js
  server/resources/services/passportSetup.js
  server/resources/services/zohoStrategy.js
  server/resources/utils/pagination/pagination.js
  server/server.js
Labels: api, backend, enhancement

#228 Admin ui enhancement
  client/web/src/Routes/PrivateRoute.jsx
  client/web/src/Routes/Routes.jsx
  client/web/src/Structure/Admin/Admin.jsx
  client/web/src/Structure/Admin/Components/AddQuestion.jsx
  client/web/src/Structure/Admin/Components/AllQuestions.jsx
  client/web/src/Structure/Admin/Components/CrudTopics.jsx
  client/web/src/Structure/Admin/Components/QuestionForm.jsx
  client/web/src/Structure/Admin/Components/QuestionUpdate.jsx
  client/web/src/Structure/Admin/Components/Questions.jsx
  client/web/src/Structure/Admin/Components/QuestionsByTopic.jsx
  client/web/src/Structure/Admin/Components/Row.jsx
  client/web/src/Structure/Admin/State/action.js
  client/web/src/Structure/Admin/State/actionTypes.js
  client/web/src/Structure/Admin/State/reducer.js
  client/web/src/Structure/Admin/Styles/QuestionsStyles.jsx
  client/web/src/Structure/Authentication/state/reducer.js
  server/resources/controller/questionController.js
Labels: enhancement

#231 scraper API added
  server/package-lock.json
  server/package.json
  server/resources/controller/scraperController.js
  server/resources/routes/scraperRoute.js
  server/resources/utils/validation/scraperValidation.js
  server/server.js
Labels: api
