Repository masai-oss/Masai_Refresh, pull requests merged in 2021-03, with the labels that each got.

#5 CRUD for topics completed
  server/resources/controller/topicController.js
  server/resources/models/Question.js
  server/resources/models/Topic.js
  server/resources/routes/topicRoute.js
  server/resources/utils/enums/QuestionTypeEnum.js
  server/resources/utils/enums/TopicsEnum.js
  server/resources/utils/validation/topicValidation.js
  server/server.js
Labels: api, backend

#13 update done
  server/resources/controller/topicController.js
  server/resources/models/Topic.js
  server/resources/routes/topicRoute.js
  server/resources/utils/enums/TopicsEnum.js
Labels: api, backend, enhancement

#10 Added : Question CRUD
  server/resources/controller/questionController.js
  server/resources/controller/topicController.js
  server/resources/models/Topic.js
  server/resources/routes/questionRoute.js
  server/resources/utils/pagination/questionPagination.js
  server/resources/utils/validation/adminValidation.js
  server/resources/utils/validation/questionValidation.js
  server/server.js
Labels: api

#23 Android authentication #18
  server/.env.example
  server/package-lock.json
  server/package.json
  server/resources/controller/authController.js
  server/resources/controller/questionController.js
  server/resources/controller/topicController.js
  server/resources/models/Question.js
  server/resources/routes/topicRoute.js
  server/resources/routes/userAuthRoute.js
  server/resources/services/passportSetup.js
  server/resources/utils/validation/adminValidation.js
  server/resources/utils/validation/questionValidation.js
  server/resources/utils/validation/topicValidation.js
Labels: api, backend

#25 submission model created
  server/resources/controller/attemptController.js
  server/resources/controller/submissionController.js
  server/resources/models/Submission.js
  server/resources/routes/attemptRoute.js
  server/resources/routes/submissionRoute.js
  server/resources/utils/enums/OutcomeEnum.js
  server/server.js
Labels: api, backend, enhancement

#28 Get topic summary and changes 2 submission model #26 #27
  server/resources/controller/attemptController.js
  server/resources/controller/submissionController.js
  server/resources/controller/topicController.js
  server/resources/models/Submission.js
  server/resources/routes/attemptRoute.js
  server/resources/routes/submissionRoute.js
  server/resources/routes/topicRoute.js
Labels: api, backend, enhancement

#29 Create results api #21
  server/package-lock.json
  server/resources/controller/questionController.js
  server/resources/models/Topic.js
Labels: api, backend

#36 attempt creation API done
  server/.gitignore
  server/package-lock.json
  server/resources/controller/attemptController.js
  server/resources/models/Submission.js
  server/resources/models/Topic.js
  server/resources/utils/enums/OutcomeEnum.js
  server/resources/utils/enums/QuestionTypeEnum.js
  server/resources/utils/enums/TopicsEnum.js
Labels: api, backend

#40 Attempt crud #31
  server/resources/controller/attemptController.js
  server/resources/routes/attemptRoute.js
Labels: api, backend

#42 minor changes to Submission model
  server/resources/controller/attemptController.js
  server/resources/models/Submission.js
Labels: api, backend, enhancement

#41 Added Topic Validation
  server/resources/controller/new.json
  server/resources/controller/test.js
  server/resources/controller/topicController.js
  server/resources/routes/topicRoute.js
  server/resources/utils/validation/topicValidation.js
Labels: api, backend, enhancement

#45 Submission Creation for new user or topic
  server/resources/controller/attemptController.js
  server/resources/routes/attemptRoute.js
Labels: api, backend

#46 attempt APIs completed - added next and record
  server/resources/controller/attemptController.js
  server/resources/controller/topicController.js
  server/resources/models/Submission.js
  server/resources/routes/attemptRoute.js
Labels: api, backend, enhancement

#59 corrections complete
  server/resources/controller/attemptController.js
  server/resources/utils/validation/attemptValidation.js
Labels: api, backend, enhancement

#61 outcome corrected in record API
  server/resources/controller/attemptController.js
  server/resources/models/Submission.js
Labels: api, backend, enhancement

#63 minor changes to asnwer type
  server/resources/controller/attemptController.js
Labels: api, backend, bug

#74 issues resolved
  client/web/package-lock.json
  client/web/src/Structure/Questions/Components/MCQ.jsx
  client/web/src/Structure/Questions/Components/SyntaxHighlighter.jsx
  client/web/src/Structure/Questions/State/action.js
  client/web/src/Structure/Results Display/Components/Results_display.jsx
  client/web/src/Structure/Results Display/State/action.js
  client/web/src/Structure/Results Display/State/reducer.js
  client/web/src/Structure/Topics/Components/Topics.js
  client/web/src/Structure/Topics/State/action.js
Labels: enhancement, frontend

#78 issues solved and data persisted
  client/web/package-lock.json
  client/web/package.json
  client/web/src/Enums/storageEnums.js
  client/web/src/Structure/Questions/Components/MCQ.jsx
  client/web/src/Structure/Questions/Components/SyntaxHighlighter.jsx
  client/web/src/Structure/Questions/State/reducer.js
  client/web/src/Structure/Questions/Styles/MCQ_styles.js
  client/web/src/Structure/Results Display/Components/Results_display.jsx
  client/web/src/Structure/Results Display/State/reducer.js
  client/web/src/Structure/Topics/State/reducer.js
  client/web/src/Utils/localStorageHelper.js
Labels: bug, enhancement, frontend

#79 New UI topic #68
  client/web/package-lock.json
  client/web/package.json
  client/web/src/Enums/storageEnums.js
  client/web/src/Routes/AdminRoute.jsx
  client/web/src/Routes/PrivateRoute.jsx
  client/web/src/Routes/Routes.jsx
  client/web/src/Structure/Admin/Components/CrudTopics.jsx
  client/web/src/Structure/Admin/Components/SearchByTopic.jsx
  client/web/src/Structure/Admin/State/action.js
  client/web/src/Structure/Authentication/Login.jsx
  client/web/src/Structure/Authentication/state/action.js
  client/web/src/Structure/Authentication/state/reducer.js
  client/web/src/Structure/Common/LoadingButton.jsx
  client/web/src/Structure/Common/Styles/LoadingButtonStyles.jsx
  client/web/src/Structure/Common/Styles/commonStyles.jsx
  client/web/src/Structure/Common/hooks/IsAdmin.jsx
  client/web/src/Structure/Common/index.js
  client/web/src/Structure/Dashboard/Dashboard.jsx
  client/web/src/Structure/Navbar/Components/SideBarList.jsx
  client/web/src/Structure/Navbar/Navbar.jsx
  client/web/src/Structure/Navbar/Styles/NavbarStyle.jsx
  client/web/src/Structure/Navbar/index.js
  client/web/src/Structure/Questions/Components/MCQ.jsx
  client/web/src/Structure/Questions/Components/SyntaxHighlighter.jsx
  client/web/src/Structure/Questions/Questions.jsx
  client/web/src/Structure/Questions/State/action.js
  client/web/src/Structure/Questions/State/reducer.js
  client/web/src/Structure/Questions/index.js
  client/web/src/Structure/Results Display/Components/Results_display.jsx
  client/web/src/Structure/Results Display/State/action.js
  client/web/src/Structure/Topics/Components/ProficiencyChart.jsx
  client/web/src/Structure/Topics/Components/Topics.js
  client/web/src/Structure/Topics/Components/iconPage.jsx
  client/web/src/Structure/Topics/Components/startQuizModal.jsx
  client/web/src/Structure/Topics/State/action.js
  client/web/src/Structure/Topics/State/reducer.js
  client/web/src/Structure/Topics/Styles/TopicStyles.jsx
  client/web/src/Structure/Topics/Topics.jsx
  client/web/src/Structure/Topics/index.js
  client/web/src/Utils/axiosInterceptor.js
  client/web/src/Utils/localStorageHelper.js
  server/resources/controller/proficiencyController.js
Labels: frontend

#85 Enhancement #82
  client/web/package-lock.json
  client/web/src/Enums/storageEnums.js
  client/web/src/Structure/Common/ProfilePic.jsx
  client/web/src/Structure/Common/index.js
  client/web/src/Structure/Navbar/Components/SideBarList.jsx
  client/web/src/Structure/Navbar/Components/logoutDialog.jsx
  client/web/src/Structure/Navbar/Navbar.jsx
  client/web/src/Structure/Navbar/Styles/NavbarStyle.jsx
  client/web/src/Structure/Questions/Components/MCQ.jsx
  client/web/src/Structure/Questions/Questions.jsx
  client/web/src/Structure/Results Display/Components/Results_display.jsx
  client/web/src/Structure/Topics/Components/startQuizModal.jsx
  client/web/src/Structure/Topics/State/reducer.js
  client/web/src/Structure/Topics/Topics.jsx
Labels: enhancement, frontend

#88 route error cleared added navbar for admin
  client/web/.env.example
  client/web/src/Routes/AdminRoute.jsx
  client/web/src/Routes/PrivateRoute.jsx
  client/web/src/Routes/Routes.jsx
  client/web/src/Structure/Authentication/state/reducer.js
  client/web/src/Structure/Common/State/action.js
  client/web/src/Structure/Common/State/actionTypes.js
  client/web/src/Structure/Common/State/reducer.js
  client/web/src/Structure/Common/hooks/IsAdmin.jsx
  client/web/src/Structure/Common/hooks/SelectedSidebar.jsx
  client/web/src/Structure/Common/index.js
  client/web/src/Structure/Navbar/Components/AdminSideBarList.jsx
  client/web/src/Structure/Navbar/Components/LogoutSideBarMenu.jsx
  client/web/src/Structure/Navbar/Components/UserSideBarList.jsx
  client/web/src/Structure/Navbar/Navbar.jsx
  client/web/src/store.js
Labels: frontend

#90 all necessary corrections made
  client/web/src/Structure/Common/TopicChip.jsx
  client/web/src/Structure/Questions/Components/MCQ.jsx
  client/web/src/Structure/Questions/Questions.jsx
  client/web/src/Structure/Questions/Styles/QuestionStyles.jsx
  client/web/src/Structure/Topics/Components/ProficiencyChart.jsx
  client/web/src/Structure/Topics/Components/iconPage.jsx
  client/web/src/Structure/Topics/Styles/TopicStyles.jsx
  client/web/src/Structure/Topics/Topics.jsx
Labels: bug, enhancement, frontend

#65 UI crud questions #16
  client/web/package-lock.json
  client/web/src/Routes/Routes.jsx
  client/web/src/Structure/Admin/Components/AllQuestions.jsx
  client/web/src/Structure/Admin/Components/QuestionForm.jsx
  client/web/src/Structure/Admin/Components/QuestionUpdate.jsx
  client/web/src/Structure/Admin/Components/Questions.jsx
  client/web/src/Structure/Admin/Components/QuestionsByTopic.jsx
  client/web/src/Structure/Admin/Components/Row.jsx
  client/web/src/Structure/Admin/State/action.js
  client/web/src/Structure/Admin/State/actionTypes.js
  client/web/src/Structure/Admin/State/reducer.js
  client/web/src/Structure/Admin/Styles/QuestionFormStyles.jsx
  client/web/src/Structure/Admin/index.js
Labels: enhancement, frontend

#91 results Ui done
  client/web/src/Structure/Common/SyntaxHighlighter.jsx
  client/web/src/Structure/Questions/Components/MCQ.jsx
  client/web/src/Structure/Results Display/Components/Results_display.jsx
  client/web/src/Structure/Results Display/Styles/ResultsPageStyle.js
Labels: enhancement, frontend

#95 logo styling done
  client/web/src/Structure/Navbar/Navbar.jsx
  client/web/src/Structure/Navbar/Styles/NavbarStyle.jsx
  client/web/src/Structure/Results Display/Styles/ResultsPageStyle.js
Labels: enhancement, frontend

#97 env example updated
  client/web/.env.example
Labels: documentation, frontend

#102 Added tooltip for chart
  client/web/src/Structure/Results Display/Components/Results_display.jsx
  client/web/src/Structure/Topics/Components/ProficiencyChart.jsx
  client/web/src/Structure/Topics/Styles/TopicStyles.jsx
Labels: enhancement, frontend

#107 corrections and enhancements completed
  client/web/package-lock.json
  client/web/package.json
  client/web/src/Structure/Results Display/Components/Results_display.jsx
  client/web/src/Structure/Results Display/Styles/ResultsPageStyle.js
  server/resources/utils/enums/TopicsEnum.js
Labels: backend, bug, enhancement, frontend

#108 tiny deletions
  client/web/src/Structure/Results Display/Components/Results_display.jsx
Labels: frontend

#109 minor changes
  client/web/src/Structure/Results Display/Components/Results_display.jsx
  client/web/src/Structure/Topics/Topics.jsx
  server/resources/controller/authController.js
  server/resources/services/googleStrategy.js
  server/server.js
Labels: enhancement

#119 Added new field to schema
  server/resources/controller/questionController.js
  server/resources/controller/reportController.js
  server/resources/models/Topic.js
  server/resources/utils/enums/ReasonEnum.js
  server/resources/utils/validation/questionValidation.js
  server/resources/utils/validation/reportValidation.js
Labels: backend

#124 changes to attempt API - next question - done
  server/resources/controller/attemptController.js
  server/resources/utils/validation/attemptValidation.js
Labels: api, backend, enhancement

#125 question verification API done
  server/resources/controller/questionController.js
  server/resources/routes/questionRoute.js
  server/resources/utils/validation/questionValidation.js
Labels: api, backend, enhancement

#132 added functionality to upload icons
  client/web/.env.example
  client/web/src/Structure/Results Display/Components/ModalReport.jsx
  client/web/src/Structure/Topics/Components/TopicCard.jsx
  client/web/src/Structure/Topics/Topics.jsx
  server/package-lock.json
  server/package.json
  server/resources/controller/topicController.js
  server/resources/helper/uploader.js
  server/resources/routes/topicRoute.js
  server/server.js
  server/uploads/2021-03-20T10:03:56.625Zserverless.svg
  server/uploads/2021-03-20T10:19:37.227Zjavascript.svg
Labels: backend

#133 Added report question
  server/package-lock.json
  server/resources/controller/reportController.js
  server/resources/models/Topic.js
  server/resources/routes/questionRoute.js
  server/resources/utils/validation/reportValidation.js
Labels: api, backend

#128 Admin topics design
  client/web/src/Structure/Admin/Components/AllQuestions.jsx
  client/web/src/Structure/Admin/Components/CrudTopics.jsx
  client/web/src/Structure/Admin/Components/IconManipulationModal.jsx
  client/web/src/Structure/Admin/Components/Questions.jsx
  client/web/src/Structure/Admin/Components/SearchByTopic.jsx
  client/web/src/Structure/Admin/State/action.js
  client/web/src/Structure/Admin/State/actionTypes.js
  client/web/src/Structure/Admin/State/reducer.js
  client/web/src/Structure/Admin/Styles/TopicsStyle.jsx
  client/web/src/Structure/Common/Message.jsx
  client/web/src/Structure/Common/index.js
  server/uploads/2021-03-21T12:20:23.086Zexpress.svg
  server/uploads/2021-03-21T12:24:51.584ZScreenshot from 2021-03-21 17-54-26.png
  server/uploads/2021-03-21T12:29:06.326ZScreenshot from 2021-03-21 17-54-21.png
  server/uploads/2021-03-21T12:30:20.145ZScreenshot from 2021-03-21 17-54-26.png
  server/uploads/2021-03-21T12:31:32.746ZScreenshot from 2021-03-21 17-54-22.png
Labels: enhancement, frontend

#136 Next api changes #135
  server/package-lock.json
  server/resources/controller/attemptController.js
  server/resources/routes/attemptRoute.js
Labels: api, backend, enhancement

#137 changes to topic crud applied
  server/resources/controller/topicController.js
  server/resources/routes/topicRoute.js
  server/resources/utils/helper/uploader.js
Labels: api, backend, bug, enhancement

#138 Added get report API
  server/resources/controller/reportController.js
  server/resources/models/Topic.js
  server/resources/routes/questionRoute.js
Labels: api, backend

#141 added api to solve report
  server/resources/controller/reportController.js
  server/resources/routes/questionRoute.js
  server/resources/utils/validation/reportValidation.js
Labels: api, backend

#145 Added Zoho authentication
  client/web/.env.example
  client/web/src/Structure/Authentication/Login.jsx
  server/.env.example
  server/package-lock.json
  server/package.json
  server/resources/routes/userAuthRoute.js
  server/resources/services/passportSetup.js
  server/resources/services/zohoStrategy.js
Labels: api, backend

#146 Correcting redux #143
  client/web/src/Routes/Routes.jsx
  client/web/src/Structure/Common/State/action.js
  client/web/src/Structure/Common/State/actionTypes.js
  client/web/src/Structure/Common/State/reducer.js
  client/web/src/Structure/Questions/State/action.js
  client/web/src/Structure/Questions/State/actionTypes.js
  client/web/src/Structure/Questions/State/reducer.js
  client/web/src/Structure/Results Display/State/action.js
  client/web/src/Structure/Results Display/State/actionTypes.js
  client/web/src/Structure/Results Display/State/reducer.js
  client/web/src/Structure/Topics/State/action.js
  client/web/src/Structure/Topics/State/actionTypes.js
  client/web/src/Structure/Topics/State/reducer.js
  server/.env.example
Labels: bug, enhancement, frontend

#148 changes made to record API
  server/resources/controller/attemptController.js
  server/resources/routes/attemptRoute.js
  server/resources/utils/validation/attemptValidation.js
Labels: api, backend, bug

#150 redux issue corrected
  client/web/src/Structure/Common/State/actionTypes.js
Labels: bug, frontend

#152 UI for topic cards and proficiency 120
  client/.DS_Store
  client/web/package-lock.json
  client/web/package.json
  client/web/src/Structure/Admin/Components/QuestionForm.jsx
  client/web/src/Structure/Authentication/Components/GoogleLogin.jsx
  client/web/src/Structure/Authentication/Components/ZohoLogin.jsx
  client/web/src/Structure/Authentication/Components/zohoIcon.svg
  client/web/src/Structure/Authentication/Login.jsx
  client/web/src/Structure/Authentication/Styles/LoginStyles.jsx
  client/web/src/Structure/Common/LoadingButton.jsx
  client/web/src/Structure/Common/Navbar2.jsx
  client/web/src/Structure/Common/index.js
  client/web/src/Structure/Navbar/Components/LogoutDialog.jsx
  client/web/src/Structure/Navbar/Components/MasaiLogo.svg
  client/web/src/Structure/Navbar/Navbar.jsx
  client/web/src/Structure/Navbar/Styles/NavbarStyle.jsx
  client/web/src/Structure/Topics/Components/ProficiencyChart.jsx
  client/web/src/Structure/Topics/Components/TopicCard.jsx
  client/web/src/Structure/Topics/Components/TopicWrapper.jsx
  client/web/src/Structure/Topics/Components/startQuizModal.jsx
  client/web/src/Structure/Topics/State/action.js
  client/web/src/Structure/Topics/State/actionTypes.js
  client/web/src/Structure/Topics/State/reducer.js
  client/web/src/Structure/Topics/Styles/TopicStyles.jsx
  client/web/src/Structure/Topics/Topics.jsx
  server/resources/controller/proficiencyController.js
Labels: backend, frontend

#154 Style changes #153
  client/web/src/App.js
  client/web/src/Resources/MasaiLogo.svg
  client/web/src/Resources/zohoIcon.svg
  client/web/src/Routes/AdminRoute.jsx
  client/web/src/Routes/PrivateRoute.jsx
  client/web/src/Routes/Routes.jsx
  client/web/src/Structure/Authentication/Components/ZohoLogin.jsx
  client/web/src/Structure/Authentication/Login.jsx
  client/web/src/Structure/Authentication/Styles/ZohoLoginStyle.js
  client/web/src/Structure/Common/Dialog.jsx
  client/web/src/Structure/Navbar/Navbar.jsx
  client/web/src/Structure/Topics/Styles/TopicStyles.jsx
  client/web/src/index.js
Labels: enhancement, frontend

#159 removed extra collection addition
  server/resources/routes/userAuthRoute.js
  server/resources/services/googleStrategy.js
  server/resources/services/zohoStrategy.js
Labels: api, enhancement

#163 refactoring done
  client/web/src/Structure/Common/CustomDialog.jsx
  client/web/src/Structure/Common/Dialog.jsx
  client/web/src/Structure/Common/LoadingButton.jsx
  client/web/src/Structure/Navbar/Navbar.jsx
  client/web/src/Structure/Topics/Components/TopicCard.jsx
  client/web/src/Structure/Topics/Components/startQuizModal.jsx
Labels: enhancement, frontend

#165 previous button issue solved
  client/web/src/Structure/Questions/Components/MCQ.jsx
  client/web/src/Structure/Questions/Styles/QuestionStyles.jsx
Labels: bug, frontend

#161 data dumping
  server/dataDumpScript/.env.example
  server/dataDumpScript/.gitignore
  server/dataDumpScript/dumpCSS.js
  server/dataDumpScript/dumpData.js
  server/dataDumpScript/dumpHTML.js
  server/dataDumpScript/dumpJS.js
  server/dataDumpScript/dumpJava.js
  server/dataDumpScript/dumpNodeJS.js
  server/dataDumpScript/dumpPython.js
  server/dataDumpScript/dumpReactJS.js
  server/dataDumpScript/dumpSQL.js
  server/resources/utils/enums/TopicsEnum.js
Labels: backend

#168 Questiion issue enchancements #166
  client/web/src/Structure/Questions/Components/MCQ.jsx
  client/web/src/Structure/Questions/Styles/QuestionStyles.jsx
Labels: bug, enhancement, frontend

#167 Reporting answers #164
  client/web/package-lock.json
  client/web/src/Enums/ReasonEnums.js
  client/web/src/Structure/Common/AlertPopUps/CustomizedSnackbars.jsx
  client/web/src/Structure/Common/AlertPopUps/Message.jsx
  client/web/src/Structure/Common/DialogBoxes/CustomDialog.jsx
  client/web/src/Structure/Common/DialogBoxes/ReportDialog.jsx
  client/web/src/Structure/Common/Styles/ReportDialogBoxStyles.js
  client/web/src/Structure/Common/Styles/commonStyles.jsx
  client/web/src/Structure/Common/Styles/commonStyles.module.css
  client/web/src/Structure/Common/index.js
  client/web/src/Structure/Navbar/Navbar.jsx
  client/web/src/Structure/Questions/Components/MCQ.jsx
  client/web/src/Structure/Questions/Components/OptionRadio.jsx
  client/web/src/Structure/Questions/State/reducer.js
  client/web/src/Structure/Questions/Styles/MCQ_styles.js
  client/web/src/Structure/Results Display/Components/ModalReport.jsx
  client/web/src/Structure/Results Display/State/action.js
  client/web/src/Structure/Results Display/State/actionTypes.js
  client/web/src/Structure/Results Display/State/reducer.js
  client/web/src/Structure/Results Display/Styles/ModalStyles.jsx
  client/web/src/Structure/Topics/Components/startQuizModal.jsx
  server/package-lock.json
  server/resources/utils/enums/ReasonEnum.js
Labels: bug, enhancement, frontend

#170 reporting bug fixed
  client/web/src/Structure/Common/DialogBoxes/ReportDialog.jsx
  client/web/src/Structure/Common/Styles/ReportDialogBoxStyles.js
Labels: bug, frontend
